version: '3.8'

services:
  q-shield-api:
    build: .
    ports:
      - "8001:8001"
    restart: always

  q-shield-frontend:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "8090:8090"
    command: python3 -m http.server 8090 --directory frontend
    restart: always
