[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "q_shield_ecdat"
version = "1.0.0"
description = "Enterprise Cryptographic Discovery & Agile Transition Tool"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "libcst",
    "click",
    "httpx",
    "pytest"
]

[project.scripts]
qshield = "q_shield.cli:cli"

[tool.setuptools]
packages = ["q_shield"]
